services:
  web:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=newsDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432