services:
  web:
    image: jetty:11.0.15-jdk17-eclipse-temurin
    ports:
      - "8080:8080"
    expose:
      - "8080:8080"
    volumes:
      - ./target/crawlers.war:/var/lib/jetty/webapps/root.war
  db:
    image: mysql:8.0.33-oracle
    environment:
      MYSQL_DATABASE: 'newsdb'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    expose:
      - "3306:3306"