spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:localhost}/${DB_NAME:newsDb}?reconnect=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/